name: video_converter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.5+6
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  ffmpeg_kit_flutter_new: ^3.2.0
  file_picker: ^10.3.3
  video_player: ^2.10.0
  path_provider: ^2.1.5
  video_trimmer: ^5.0.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  gallery_saver_plus: ^3.2.9
  android_intent_plus: ^6.0.0
  flutter_local_notifications: ^18.0.1
  in_app_update: ^4.2.5
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^10.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - shorebird.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#5F8F3C"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
